name: Update My M3U Playlist

on:
  schedule:
    # รันอัตโนมัติทุกวัน เวลา 00:00 น. (เวลา UTC) หรือ 07:00 น. เวลาไทย
    - cron: '0 0 * * *'
  workflow_dispatch: # ปุ่มกดรันเองแบบ Manual

jobs:
  update-playlist:
    runs-on: ubuntu-latest
    permissions:
      contents: write # อนุญาตให้บอทเขียนไฟล์ลง Repo ได้

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install requests

    - name: Run script
      run: python epg_script.py # 👈 เปลี่ยนให้ตรงกับชื่อไฟล์ Python ของคุณ

    - name: Commit and Push changes
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add TV_epg.xml # 👈 เปลี่ยนเป็นชื่อไฟล์ XML ที่สคริปต์สร้างออกมา
        git commit -m "Update EPG data" || exit 0 # หากไม่มีการเปลี่ยนแปลงจะข้ามไป ไม่สั่งให้ Actions ขึ้นสีแดง
        git push
